[FE] Create account details page
framgia/sph-flutter pull request #14
Opened 2023-06-14 10:33 UTC by rdelrosariojr

2023-06-15 06:00 UTC, Dbulawan13 commented
Comment:

- [ ] When user click the percentage of the donut graph. It should expand based on figma.
For Reference: https://pub.dev/packages/fl_chart

Once this PR is merge https://github.com/framgia/sph-flutter/pull/12 and https://github.com/framgia/sph-flutter/pull/16 . Please update this so that the buttons will work properly.
Expected result:

https://github.com/framgia/sph-flutter/assets/86758474/42b4e319-0adc-441c-a4f9-4e33105eaca8

Comment: 1

2023-06-16 09:49 UTC, Dbulawan13 commented
Comment:

- [ ] Deposit, Withdraw, and Transfer component will not appear once user click on the button

https://github.com/framgia/sph-flutter/assets/86758474/0b20bea0-f015-48c5-baa2-43e1680a94f8

Comment: 1

2023-06-21 05:42 UTC, Dbulawan13 approved these changes, later dismissed
Approve PR #14 

Working:
- I am able to create an account details page.
- I am able to display the Deposit, Withdraw, and Transfer components once the button is clicked.
- I will redirect to the transaction history page once the transaction button is clicked.

https://github.com/framgia/sph-flutter/assets/86758474/35f9fb2b-cf1d-4a83-b209-ba90ee9302b1

Testing Hours: 2
Comments: 2
Iterations: 2

2023-06-21 06:03 UTC, RDLegs approved these changes, later dismissed
Looks good to me!

You missed to add accountId in `toJson()` but we can change that during the implementation task

2023-06-21 06:04 UTC, jstephend-sun requested changes
Requested Changes #14

review time: 10mins
comments: 10

2023-06-21 06:04 UTC, jstephend-sun commented on frontend/lib/src/components/balance_card.dart
> +class BalanceCard extends StatelessWidget {
provide description for the widget and its parameters

2023-06-21 06:04 UTC, jstephend-sun commented on frontend/lib/src/components/button.dart
> +    this.buttonColor = const Color(0xFF00CCFF),
add descriptions for the parameters

2023-06-21 06:04 UTC, jstephend-sun commented on frontend/lib/src/components/graph.dart
> +class Graph extends StatefulWidget {
use of stateless widget

2023-06-21 06:04 UTC, jstephend-sun commented on frontend/lib/src/components/graph.dart
> +class Graph extends StatefulWidget {
provide description to the widget

2023-06-21 06:04 UTC, jstephend-sun commented on frontend/lib/src/components/graph.dart
> +  int touchedIndex = -1;
use getxController

2023-06-21 06:04 UTC, jstephend-sun commented on frontend/lib/src/components/graph.dart
> +  int touchedIndex = -1;
can we use other name like focus? haha

2023-06-21 06:04 UTC, jstephend-sun commented on frontend/lib/src/components/indicator.dart
> +class Indicator extends StatelessWidget {
widget description

2023-06-21 06:04 UTC, jstephend-sun commented on frontend/lib/src/components/indicator.dart
> +  final Color color;
```suggestion
  });
  
  final Color color;
```
space

2023-06-21 06:04 UTC, jstephend-sun commented on frontend/lib/src/components/indicator.dart
> +    required this.color,
parameter descriptions

2023-06-21 06:04 UTC, jstephend-sun commented on frontend/lib/src/components/indicator.dart
> +          style: TextStyle(
use label large and apply bold

2023-06-21 06:04 UTC, jstephend-sun commented on frontend/lib/src/features/account_details/account_details_page.dart
> +    // this is temporary, this is to verify that the argument was pass successfully
add TODO in the comment so it can be found easily

2023-06-21 06:04 UTC, jstephend-sun commented on frontend/lib/src/models/account.dart
> +        accountId: json["account_id"],
wrong key, refer to database

2023-06-21 09:17 UTC, rdelrosariojr commented on frontend/lib/src/components/graph.dart
> +class Graph extends StatefulWidget {
@jstephend-sun I declared dynamic variable focusIndex, correct me if I'm wrong, we can't use stateless for this one.

2023-06-21 09:28 UTC, jstephend-sun approved these changes
Approved #14

review time: 10mins
comments: 10

2023-06-21 09:30 UTC, merged