SIM_FLUTTER-27 [FE] Create user profile page
framgia/sph-flutter pull request #16
Opened 2023-06-15 04:00 UTC by egiegarciano14

### Issue Links
- backlog
- 
- [figma](https://www.figma.com/file/uzAwGmOCLvGbReXshnT3UN/SAVINGS-APP?type=design&node-id=486-216&t=Qj4jHIwspVgbmfia-0)

### Definition of Done
- Create User profile page
- User can navigate to user profile change password page

### Notes
- UI only
- Validation can be included in integration task
- For the creation of bottom bar, it will be a separate task 

### Attachments
![image](https://github.com/framgia/sph-flutter/assets/79126024/7e81be00-f47c-4dcd-a664-f4bc7cc6688f)
![image](https://github.com/framgia/sph-flutter/assets/79126024/d6bc0de5-0328-4de3-baca-6f81490c340a)

2023-06-15 06:16 UTC, Dbulawan13 approved these changes, later dismissed
Approve PR #16 

Working:
- Created history page
- Able to create components for filter transaction by type and date

https://github.com/framgia/sph-flutter/assets/86758474/ce58e23d-5f1e-40d3-99eb-80f505de4003

Testing Hours: 0.08
Comment: 0
Iteration: 0

2023-06-19 09:05 UTC, RDLegs requested changes

2023-06-19 09:05 UTC, RDLegs commented on frontend/lib/src/features/transaction_history/data/data.dart
> +List<Map<String, String>> transactionData = [
Create a `Transaction` model based on this data and make a `List<Transaction>` instead.

You can see an implementation of this in the dashboard

2023-06-19 09:05 UTC, RDLegs commented on frontend/lib/src/features/transaction_history/components/transaction_card.dart
> +        ...transactionData.map(
Use `ListView.builder()` instead

2023-06-19 09:05 UTC, RDLegs commented on frontend/lib/src/features/transaction_history/components/transaction_card.dart
> +                        data['description']!,
It's much better to map the data from JSON to a model object in Flutter to make things easier.

This is to avoid directly manipulating the JSON data in the screens and instead will be delegated to the model class.

2023-06-19 09:05 UTC, RDLegs commented on frontend/lib/src/features/transaction_history/data/data.dart
> +List<Map<String, String>> transactionData = [
You can use quickytype.io as a way to make class files easily

2023-06-19 09:05 UTC, RDLegs commented on frontend/lib/src/features/transaction_history/components/transaction_card.dart
> +            return Container(
Please refactor and extract this widget to a separate component

2023-06-19 10:33 UTC, RDLegs commented on frontend/lib/src/features/transaction_history/transaction_history.dart
> +class TransactionHistory extends StatefulWidget {
Please change this to StatelessWidget and utilize GetX

2023-06-20 08:38 UTC, rdelrosariojr reviewed
reviewed time: 0.8
comments: 3

2023-06-20 08:38 UTC, rdelrosariojr commented on frontend/lib/src/features/transaction_history/transaction_history.dart
> +              DatePickerField(
Since this is a date filter for Transaction History, please modify the DatePickerField by adding `lastDate`, so that we can optionally disable future dates.

2023-06-20 08:38 UTC, rdelrosariojr commented on frontend/lib/src/features/transaction_history/transaction_history.dart
> +                ListView.builder(
add also a display if there is no transaction history. A simple "No transaction record" will do.

2023-06-20 08:38 UTC, rdelrosariojr commented on frontend/lib/src/components/dropdown.dart
> +class Dropdown extends StatelessWidget {
We can move this file to `components/input` folder

2023-06-20 08:46 UTC, egiegarciano14 commented on frontend/lib/src/features/transaction_history/transaction_history.dart
> +              DatePickerField(
@rdelrosariojr pls give example about this, I'm not sure what you mean about this

2023-06-20 09:16 UTC, rdelrosariojr reviewed
reviewed time: 0.02
comments: 1

2023-06-20 09:16 UTC, rdelrosariojr commented on frontend/lib/src/components/input/date_picker_field.dart
> +              lastDate: DateTime.now(),
make it a prop to make it more dynamic. Other usage for this component doesn't necessarily need to disable all future dates.

2023-06-20 09:19 UTC, rdelrosariojr reviewed
APPROVED PR16

reviewed time: 0.83
comments: 4

2023-06-21 02:40 UTC, RDLegs approved these changes
LGTM!

2023-06-21 02:44 UTC, merged