[SIM_FLUTTER-52] [BE] Create Get Transactions API
framgia/sph-flutter pull request #23
Opened 2023-06-22 03:17 UTC by IanUrriza10

### Issue Links
- [backlog](https://framgiaph.backlog.com/view/SIM_FLUTTER-52)
- [slack](https://sun-philippine.slack.com/archives/C059L7XAXFB/p1687246980761349)
###  Notes
- first truncate transactions table
    - `php artisan db`
    -  `truncate transactions` then `exit`
- create transactions
    - `php artisan db:seed --class=TransactionSeeder` (takes time as there's 1 sec delay per insert)

- visit URLs
    - http://127.0.0.1:8000/api/transactions
    - http://127.0.0.1:8000/api/accounts/{account_id}
    - http://127.0.0.1:8000/api/users/{user_id}/accounts

- For Testing
    - Use login first to get a `user_id` 
    - Use Show accounts via user_id to set the first `account_id`
    - All routes are now accessible in Transactions Collection
### Definition of done
- [x] create api/transactions route
- [x] display all transactions from the database
- [x] display all transactions of a specific account

### Screenshots

2023-06-22 05:03 UTC, Dbulawan13 commented
Comment:

- [ ] transaction cannot be fetch when sending via `{{api}}/accounts/{{account_id}}/transactions` since account_id is empty in global tab.

https://github.com/framgia/sph-flutter/assets/86758474/95957a30-b97b-437d-917e-56a3483d3c07

- [ ] The user_id is not the same when fetching the transaction via {`{api}}/transactions/{{transaction_id}}` maybe because some transaction_id is `NULL`
![2023-06-22_12-55](https://github.com/framgia/sph-flutter/assets/86758474/2373ea58-ad16-42a2-864e-935a2a5e7cb2)

![2023-06-22_12-58](https://github.com/framgia/sph-flutter/assets/86758474/a5382bc5-30cb-4478-b0b4-7b6193165777)

Testing Hours: 0.50
Comments: 2

2023-06-22 05:20 UTC, Dbulawan13 approved these changes, later dismissed
Approve PR #23 

Working:
- Able to Get transactions
   - via `ALL Accounts`
   - via `{{api}}/accounts/{{account_id}}/transactions `
   - via `{{api}}/transactions/{{transaction_id}}`

![2023-06-22_13-18_1](https://github.com/framgia/sph-flutter/assets/86758474/ed2d7415-c78f-42a2-aba5-b5058d3f0e10)
![2023-06-22_13-18](https://github.com/framgia/sph-flutter/assets/86758474/c479865d-b79f-4c48-954f-f5f6261ff19f)
![2023-06-22_13-17](https://github.com/framgia/sph-flutter/assets/86758474/89c48f68-b96e-470c-b1ae-20e3d5a83fc5)

Testing Hours: 1
Comment: 0
Iteration: 0

2023-06-23 02:35 UTC, jstephend-sun requested changes
initial comments

2023-06-23 02:35 UTC, jstephend-sun commented on backend/app/Http/Controllers/TransactionController.php
> +        //For /accounts/{account_id}/transactions
```suggestion
    {

        // For /accounts/{account_id}/transactions
```

2023-06-23 02:35 UTC, jstephend-sun commented on backend/app/Http/Controllers/TransactionController.php
> +        //For /accounts/{account_id}/transactions
```suggestion
    {
        //For /accounts/{account_id}/transactions
```

2023-06-23 02:35 UTC, jstephend-sun commented on backend/app/Http/Controllers/TransactionController.php
> +            //For shallow nesting
```suggestion
            // For shallow nesting
```

2023-06-23 02:35 UTC, jstephend-sun commented on backend/app/Http/Controllers/TransactionController.php
> +            // see https://laravel.com/docs/10.x/controllers#shallow-nesting
```suggestion
            // see https://laravel.com/docs/8.x/controllers#shallow-nesting
```

2023-06-23 02:35 UTC, jstephend-sun commented on backend/app/Http/Controllers/TransactionController.php
> +        //For /transactions
```suggestion
        // For /transactions
```

2023-06-23 07:55 UTC, jstephend-sun approved these changes
Approved #23

review time: 5mins
comments: 1

2023-06-23 07:58 UTC, merged