[SIM_FLUTTER-38] [BE] Create search user API
framgia/sph-flutter pull request #25
Opened 2023-06-22 10:20 UTC by egiegarciano14

### Issue Links
- [backlog](https://framgiaph.backlog.com/view/SIM_FLUTTER-38)
- [slack](https://sun-philippine.slack.com/archives/C059L7XAXFB/p1687429475998349)

###  Notes
- Go to postman
- Login as Admin, users where `is_admin` is 1

- Route is 
![image](https://github.com/framgia/sph-flutter/assets/79126024/938bc8c4-0fc5-4214-a11f-5e3120c39a56)

- Input a value for the keyword
![image](https://github.com/framgia/sph-flutter/assets/79126024/0cb2afe4-5214-44a0-80cb-a6ca0f0a4f60)

- If no user found
![image](https://github.com/framgia/sph-flutter/assets/79126024/978ec872-da82-4a79-85d1-d603400cb2c1)

- Can search by first name
- Can search by middle name
- Can search by last name
- Can search by first and last name
- Can search by full name
- Admin can only search users who are not admin

- Refer to the `first_name` , `middle_name` , and `last_name`  column

### Definition of done
- [x] Create search user API

2023-06-22 10:30 UTC, karlolee50 requested changes

2023-06-22 10:30 UTC, karlolee50 commented on backend/app/Http/Controllers/UserController.php
> +        $s = $request['search_value'];
please rename variable. use a descriptive variable name

2023-06-22 10:30 UTC, karlolee50 commented on backend/routes/api.php
> +    Route::get('search', [UserController::class, 'search']);
will the resulting route be just `/search`?

since this is search for users, can we have it something like this
`/users/search`

2023-06-22 10:30 UTC, karlolee50 commented on backend/app/Http/Controllers/UserController.php
> +            return UserResource::make(array_merge(['message' => 'User not found.']));
what will be the sent result to the web application? just an empty array?

2023-06-23 02:27 UTC, jstephend-sun requested changes
Requested Changes #25

2023-06-23 02:27 UTC, jstephend-sun commented on backend/app/Http/Controllers/UserController.php
> +            })->get();
move db logic to the model

2023-06-23 02:27 UTC, jstephend-sun commented on backend/app/Http/Controllers/UserController.php
> +            return UserResource::make(array_merge(['message' => 'User not found.']));
i agree, since its search, we can return empty array lang

2023-06-23 05:56 UTC, egiegarciano14 commented on backend/app/Http/Controllers/UserController.php
> +            return UserResource::make(array_merge(['message' => 'User not found.']));
I change the code, if no user found it will return an empty array, as suggested by sir Stephen
`{
    "data": []
}`

2023-06-23 08:40 UTC, Dbulawan13 submitted a review, later dismissed
Approve PR #25 

Working:
- Able to create search user API
- Able to search user by firstname, middlename, and lastname as keyword

![2023-06-23_16-39](https://github.com/framgia/sph-flutter/assets/86758474/29683baa-460c-4059-971e-1a049c05ed96)
![2023-06-23_16-38_1](https://github.com/framgia/sph-flutter/assets/86758474/7f356547-29ee-4204-a29f-bb00a790965a)
![2023-06-23_16-38](https://github.com/framgia/sph-flutter/assets/86758474/e99027bb-266c-4550-96fd-a8d8d70fe1f1)

Testing hours: 1
Comment: 0
Iteration: 0

2023-06-27 02:27 UTC, jstephend-sun requested changes
Requested Changes #25

follow up on previous comment to move code block to Model

2023-06-27 02:27 UTC, jstephend-sun commented on backend/app/Http/Requests/SearchUserRequest.php
> +        return false;
simplify

2023-06-27 02:27 UTC, jstephend-sun commented on backend/app/Http/Requests/SearchUserRequest.php
> +            'keyword' => [],
add required validation, can also include a-z characters only or something like that

2023-06-29 01:57 UTC, jstephend-sun approved these changes
Approved #25

2023-06-29 02:11 UTC, karlolee50 approved these changes

2023-06-29 02:14 UTC, merged