SIM_FLUTTER-6 [BE] Create reset password API
framgia/sph-flutter pull request #31
Opened 2023-06-26 07:38 UTC by CaneteJoash

#### Backlog link
- https://framgiaph.backlog.com/board/SIM_FLUTTER?selectedIssueKey=SIM_FLUTTER-36&category=365505

#### Definition of done
- [x] user should be able to request forgot password
- [x] user should be able to receive reset password link in email 
- [x] user should be able to create his new password

#### Steps

**1. Set up env**

1. create `mailtrap account`
     - if you have already mailtrap account you can proceed to next step
2. Click `add Inbox`
![image](https://github.com/framgia/sph-flutter/assets/89382909/ea5b836d-21d4-47a3-9926-1538ef39cca8)

3. Name it `sph-flutter` and then click `save`
![image](https://github.com/framgia/sph-flutter/assets/89382909/c0061ab3-6242-44c1-a214-c0d608ee5e64)

4. Once save Click `sph-flutter` and change the `cURL` to `Laravel 7+'
![image](https://github.com/framgia/sph-flutter/assets/89382909/bdbec919-0b04-413f-8cfc-fcf7bd46c779)

5. update your `.env file` and add your credentials. 
- for you `MAIL_PASSWORD` you can view it in `show credentials`
![image](https://github.com/framgia/sph-flutter/assets/89382909/16b4d65b-4e56-4c4b-b7e3-baa80c9a0fa4)

6. Refer to my `.env file` for reference  you can copy the line found in `.env.example`
![image](https://github.com/framgia/sph-flutter/assets/89382909/c587a5f4-5b6b-42ee-b377-1dac14f4e094)

**2. Forgot password**
1. open postman and click the `post forgot_password` under auth collection
- input your email and click send
![image](https://github.com/framgia/sph-flutter/assets/89382909/4379f635-2b88-4a87-b540-7722392f4777)

**3. Resetting password or change password**
1. open [Mailtrap](https://mailtrap.io/inboxes) and click the message  and copy the link below
![image](https://github.com/framgia/sph-flutter/assets/89382909/7949a683-f8b5-4881-928d-1c96b4911829)

2. paste the link in post man
- open new tab in post man and paste the link you copied 
- change the method to `POST`
- click `body` and then click `form-data`
- add `email`, `password` and `password_confirmation` key
- then put your email, new password and confirm password value 
- then click send
![image](https://github.com/framgia/sph-flutter/assets/89382909/9222af5d-099e-47f1-bb55-3bd2de27e973)

#### RECORDINGS 
![1](https://github.com/framgia/sph-flutter/assets/89382909/960bbd01-0f85-466a-be19-2f1dae5ccc60)

2023-06-26 08:32 UTC, Dbulawan13 commented
Comment:

- [ ] Please add a validation that prevents the user from resetting their password to be the same as their old password.

![image](https://github.com/framgia/sph-flutter/assets/86758474/9b53b0c9-601f-4894-ad13-d1e22c00a642)

Comment: 1

2023-06-26 08:58 UTC, jstephend-sun requested changes
Requested Changes #31

review time: 15mins
comments: 7
iteration: 1st review

2023-06-26 08:58 UTC, jstephend-sun commented on backend/routes/api.php
> +Route::post('forgot.password', [AuthController::class, 'forgotPassword']);
is there any specific reason as to why " . " (dot) is being used here?

this is not a resourceful route so i dont think   .   is suited to be used here for declaring the route

2023-06-26 08:58 UTC, jstephend-sun commented on backend/app/Http/Controllers/AuthController.php
> +            return response()->json(['message' => 'The link was sent, please check your email']);
use Resource for response

2023-06-26 08:58 UTC, jstephend-sun commented on backend/app/Http/Controllers/AuthController.php
> +            return response()->json(['message' => trans('auth.email')], 401);
use resource for response

2023-06-26 08:58 UTC, jstephend-sun commented on backend/app/Http/Controllers/AuthController.php
> +    public function reset(ResetRequest $request)
```suggestion
    public function reset?(ResetRequest $request)
```

be more descriptive for the function name

2023-06-26 08:58 UTC, jstephend-sun commented on backend/app/Http/Controllers/AuthController.php
> +            $request->only('email', 'password', 'password_confirmation', 'token'),
any reason why is "password_confirmation" being retrieved here?

use function `validated()` to retrieve validated inputs

2023-06-26 08:58 UTC, jstephend-sun commented on backend/app/Http/Controllers/AuthController.php
> +            return response()->json(['message' => 'Password was reset successfully'], 201);
make use of Resource as response

2023-06-26 08:58 UTC, jstephend-sun commented on backend/app/Http/Requests/Auth/ResetRequest.php
> +class ResetRequest extends FormRequest
```suggestion
class Reset?Request extends FormRequest
```

be more descriptive

2023-06-27 07:19 UTC, jstephend-sun requested changes
Requested Changes 

additional review time: 1hr
comments: 8

2023-06-27 07:19 UTC, jstephend-sun commented on backend/app/Http/Controllers/AuthController.php
> +        $userEmail = $request->validated();
```suggestion
        $ = $request->validated();
```
variable name seems inappropriate

2023-06-27 07:19 UTC, jstephend-sun commented on backend/app/Http/Controllers/AuthController.php
> +            $request->only('email', 'password', 'token'),
```suggestion
            $->only('email', 'password', 'token'),
```
use already extracted input data

2023-06-27 07:19 UTC, jstephend-sun commented on backend/app/Models/User.php
> +        $url = '{{api}}/reset-password?token=' . $token;
```suggestion
        $url = '?{{api}}?/reset-password?token=' . $token;
```
why are you putting the postman variable here? do we expect users to have the same postman setup?

2023-06-27 07:19 UTC, jstephend-sun commented on backend/app/Models/User.php
> +        $this->notify(new ResetPasswordNotification($url));
```suggestion
        $this->notify(new ResetPasswordNotification($token));
```
remove above $uri
we should send directly the token, we dont have web for laravel

2023-06-27 07:19 UTC, jstephend-sun commented on backend/app/Notifications/ResetPasswordNotification.php
> +    protected $url;
remove

2023-06-27 07:19 UTC, jstephend-sun commented on backend/app/Notifications/ResetPasswordNotification.php
> +        $this->url = $url;
```suggestion

```
remove

2023-06-27 07:19 UTC, jstephend-sun commented on backend/app/Notifications/ResetPasswordNotification.php
> +    public function __construct(string $url)
```suggestion
    public function __construct(protected string $token)
```
immediately set class properties from constructor

2023-06-27 07:19 UTC, jstephend-sun commented on backend/app/Notifications/ResetPasswordNotification.php
> +                    ->action('Click to reset', $this->url)
```suggestion
->line("Copy reset token $this->token")
```

notify user to copy reset token

2023-06-27 10:09 UTC, Dbulawan13 approved these changes, later dismissed
Approve PR #31 

Working:
- Able to change password successfully
- Unable to change password, if password does not match 
- Unable to change password, if new password is the same as the old password
- Unable to change password if email is incorrect.

![2023-06-27_18-05](https://github.com/framgia/sph-flutter/assets/86758474/36167115-d240-47c0-b0d1-e5a7eb8377d3)
![2023-06-27_17-59_2](https://github.com/framgia/sph-flutter/assets/86758474/83d4b02b-ae15-4a55-9823-4c0f6906ee59)
![2023-06-27_17-59_1](https://github.com/framgia/sph-flutter/assets/86758474/488a7067-f8a7-43bd-b28a-0e1a4125005a)
![2023-06-27_17-59](https://github.com/framgia/sph-flutter/assets/86758474/b66bec9f-b6e7-4a92-9fff-4fb3665ba12a)

Testing Hours: 2
Comment: 1
Iteration: 1

2023-06-29 01:38 UTC, jstephend-sun approved these changes
Approved #31

additional review time: 1hr
comments: 8
iteration: 2nd comment

2023-06-29 01:45 UTC, merged