[SIM_FLUTTER-73] [BE] Create Withdraw API
framgia/sph-flutter pull request #35
Opened 2023-06-27 09:48 UTC by IanUrriza10

### Issue Links
- [backlog](https://framgiaph.backlog.com/view/SIM_FLUTTER-73)
- [slack]()

###  Notes
- URLs
    - POST http://127.0.0.1:8000/api/accounts/{account_id}/transactions

- For Testing
    - Use `/login` first to get a `user_id` 
    - Use `Show accounts via user_id` to set the first `account_id`
    - Use Insert Transaction (Transfer with the body found in screenshot)
    - If transactions cannot occur due to negative balance
        - `php artisan db`
        - `truncate transactions`
        - `exit`
        - `php artisan db:seed --class=TransactionSeeder` 

### Definition of done
- [x] filter out TRANSFER type transaction
- [x] Add Response on successful insert 

### Screenshots
![image](https://github.com/framgia/sph-flutter/assets/114897466/f5f06bc0-95a1-4a2b-9983-d551af1a3a2a)

2023-06-30 02:36 UTC, Dbulawan13 approved these changes, later dismissed
Approve PR #35 

Working:
- Able to withdraw if user has remaining balance
- Unable to withdraw if user has insufficient balance

![2023-06-30_10-34_2](https://github.com/framgia/sph-flutter/assets/86758474/c4eb746d-9c18-4665-8348-f2d521c037e5)
![2023-06-30_10-34](https://github.com/framgia/sph-flutter/assets/86758474/9fe286b4-6fe1-4b1d-a04e-a0f656c3d697)

![2023-06-30_10-34_1](https://github.com/framgia/sph-flutter/assets/86758474/ad28319e-6fcc-47cd-a2ee-190fbd2891f6)

Testing Hours: 0.16
Comment: 0
Iteration: 0

2023-06-30 04:40 UTC, jstephend-sun requested changes
Requested Changes #35

review time: 10mins
comments: 5

2023-06-30 04:40 UTC, jstephend-sun commented on backend/app/Http/Controllers/TransactionController.php
> +        DB::beginTransaction();
use DB::transaction(function () {.... https://laravel.com/docs/8.x/database#database-transactions
theres no custom code for the catch code anyways

also 
![image](https://github.com/framgia/sph-flutter/assets/95029803/eeeb2331-cf2b-4c2a-b47a-2a338cf2cf30)

2023-06-30 04:40 UTC, jstephend-sun commented on backend/app/Http/Controllers/TransactionController.php
> +    public static function creditTransaction(Account $account, $payload)
refactor so that the api endpoint functions show first, 
ex

index
show

..
creditTransaction
transferTransaction

2023-06-30 04:40 UTC, jstephend-sun commented on backend/app/Http/Controllers/TransactionController.php
> +    public static function creditTransaction(Account $account, $payload)
```suggestion
    public? static function creditTransaction(Account $account, $payload)
```

is there a need for this to be public?

2023-06-30 04:40 UTC, jstephend-sun commented on backend/app/Http/Controllers/TransactionController.php
> +    public static function creditTransaction(Account $account, $payload)
```suggestion
    public static? function creditTransaction(Account $account, $payload)
```
is there a need for this to be static?

2023-07-03 03:13 UTC, jstephend-sun approved these changes
Approved #35

review time: 10mins
comments: 5
iteration: 1st comment

2023-07-03 03:31 UTC, merged