[SIM_FLUTTER-18][Integrate] Display User updated profile details dynamically
framgia/sph-flutter pull request #37
Opened 2023-06-29 10:36 UTC by rdelrosariojr

2023-07-03 09:45 UTC, RDLegs reviewed
I left some minor comments

2023-07-03 09:45 UTC, RDLegs commented on frontend/lib/src/features/user_profile/profile_info.dart
> +      final editProfile = await NetworkConfig().client.put(
Refactor this inside `user_service.dart`

2023-07-03 09:45 UTC, RDLegs commented on frontend/lib/src/services/user_profile_service.dart
> +import 'dart:io';
I think we can transfer this insider `user_service.dart`

No need to create a new service.

2023-07-03 10:04 UTC, RDLegs commented on frontend/lib/src/controllers/user_profile_controller.dart
> +  final RxString _userName = ''.obs;
Change this implementation from `RxString` to an observable `User` model

https://www.youtube.com/watch?v=NrtIfLPleBY

2023-07-03 10:21 UTC, jstephend-sun requested changes
requested changes

2023-07-03 10:21 UTC, jstephend-sun commented on frontend/lib/src/components/input/input_field.dart
> +    this.enabled = true,
parameter description

2023-07-03 10:21 UTC, jstephend-sun commented on frontend/lib/src/features/user_profile/profile_info.dart
> +import 'dart:io';
dart
<space>
package
<space>
internal

for consistency

2023-07-03 10:21 UTC, jstephend-sun commented on frontend/lib/src/features/user_profile/profile_info.dart
> +import '../../components/input/date_picker_field.dart';
this can be changed to internal package reference

2023-07-03 10:21 UTC, jstephend-sun commented on frontend/lib/src/features/user_profile/profile_info.dart
> +            : GestureDetector(
refactor
avoid ternary expression for large code blocks


if isloading {
  return circ
}

return gesture

2023-07-03 10:22 UTC, Dbulawan13 submitted a review, later dismissed
Approve PR #37

Working:
- Able to dynamically display user profile details
- Able to update user profile details
- Email and Username is disable by default. User/Admin cannot update the email and username
- Save button will be disable if required fields are empty

https://github.com/framgia/sph-flutter/assets/86758474/e13c1098-97c1-4a33-b67f-0822ec5ac9d9

Testing Hours: 0.38
Comment: 0
Iteration: 0

2023-07-04 02:45 UTC, jstephend-sun approved these changes, later dismissed
approved on my end

2023-07-05 05:41 UTC, RDLegs submitted a review, later dismissed

2023-07-05 05:42 UTC, RDLegs approved these changes, later dismissed
LGTM!

2023-07-05 05:48 UTC, jstephend-sun approved these changes, later dismissed
for merge

2023-07-05 06:01 UTC, Dbulawan13 submitted a review, later dismissed
Approve PR https://github.com/framgia/sph-flutter/pull/37

Working:
- Able to dynamically display user profile details
- Able to update user profile details
- Email and Username is disable by default. User/Admin cannot update the email and username
- Save button will be disable if required fields are empty

https://github.com/framgia/sph-flutter/assets/86758474/f0e6701c-b7aa-4a1f-9956-15d761978dea

Testing Hours: 1
Comment: 0
Iteration: 0

2023-07-05 06:24 UTC, jstephend-sun approved these changes

2023-07-05 06:25 UTC, merged