[BE] Create DB migrations
framgia/sph-flutter pull request #4
Opened 2023-06-09 03:47 UTC by rdelrosariojr

**Issue Link**
- [BackLog](https://framgiaph.backlog.com/board/SIM_FLUTTER?selectedIssueKey=SIM_FLUTTER-44)

**Definition of done**
- [x] [BE] Creating DB migration

**Note**
- If you have run the initial migration before, please run `php artisan migrate:rollback`, this is because I updated the User migration and we need to revert that initial migration we did.
- then run `php artisan migrate` again

**Attachment**
![image](https://github.com/framgia/sph-flutter/assets/97145763/7ab5a2b5-2824-4606-bf62-1dbc867aa9b1)

2023-06-09 05:58 UTC, karlolee50 requested changes

2023-06-09 05:58 UTC, karlolee50 commented on backend/database/migrations/2014_10_12_000000_create_users_table.php
>              $table->id();
can you make it uuid instead of incrementing integer?

2023-06-09 05:58 UTC, karlolee50 commented on backend/database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->boolean('is_admin');
default to false

2023-06-09 05:58 UTC, karlolee50 commented on backend/database/migrations/2023_06_09_025916_create_accounts_table.php
> +            $table->id();
use uuid

2023-06-09 05:58 UTC, karlolee50 commented on backend/database/migrations/2023_06_09_025950_create_transactions_table.php
> +            $table->id();
use uuid

2023-06-09 05:58 UTC, karlolee50 commented on backend/database/migrations/2023_06_09_025950_create_transactions_table.php
> +            $table->enum('category',[0, 1, 2, 3, 4, 5, 6]);
are there description which value means which? for example:

transaction_type = 0 means deposit

2023-06-09 08:56 UTC, karlolee50 requested changes

2023-06-09 08:56 UTC, karlolee50 commented on backend/database/migrations/2014_10_12_000000_create_users_table.php
>              $table->timestamp('email_verified_at')->nullable();
ah i think we can remove this. we will not have a verify email feature rigth? we can add it in the future if ever

2023-06-09 08:56 UTC, karlolee50 commented on backend/database/migrations/2023_06_09_025950_create_transactions_table.php
> +            $table->timestamps();
is it possible to add user_id foreign key here as well?

2023-06-09 09:58 UTC, karlolee50 approved these changes

2023-06-13 06:50 UTC, Dbulawan13 approved these changes
Approve PR #4 

Working:
- The migration was completed successfully.
- No errors were encountered during the migration process.
- The Accounts, Transactions, and Users tables were created.
- The column names and data types are correct.

![2023-06-13_14-47](https://github.com/framgia/sph-flutter/assets/86758474/023b05fa-6f06-41a1-89c0-d22554486afd)
![2023-06-13_14-46](https://github.com/framgia/sph-flutter/assets/86758474/1cdae303-28ee-48bc-a0be-250d6fe516b9)
![2023-06-13_14-45](https://github.com/framgia/sph-flutter/assets/86758474/78c93fe9-bed1-4638-8b9f-b5244fb0ee54)
![2023-06-13_14-20](https://github.com/framgia/sph-flutter/assets/86758474/f0ba37a9-a396-4c28-9d35-53fa8b29d5d1)

Testing Hours: 0.50
Comment: 0
Iteration: 0

2023-06-13 06:59 UTC, merged