[SIM_FLUTTER-46] [INTEGRATE] Create and implement admin delete user
framgia/sph-flutter pull request #42
Opened 2023-07-03 10:04 UTC by egiegarciano14

### Issue links
- [Backlog](https://framgiaph.backlog.com/view/SIM_FLUTTER-46)
- Slack

### Definition of Done
- [x] Admin can delete user

### Note
- Dependent to [pr#39](https://github.com/framgia/sph-flutter/pull/39)

### Recording
![image](https://github.com/framgia/sph-flutter/assets/79126024/04a8d487-a551-402e-9648-06cc5fcb54a6)

2023-07-03 10:47 UTC, jstephend-sun requested changes
Requested Changed #42

review time: 10mins
comments: 3

2023-07-03 10:47 UTC, jstephend-sun commented on frontend/lib/src/services/user_service.dart
> +  static Future<dynamic> deleteUser(String id) async {
```suggestion
  static Future<void> deleteUser(String id) async {
```
function doesnt have any return

2023-07-03 10:47 UTC, jstephend-sun commented on frontend/lib/src/controllers/admin_user_list_controller.dart
> +  Future<dynamic> deleteUser(String id) async {
```suggestion
  Future<void> deleteUser(String id) async {
```
no return

2023-07-03 10:47 UTC, jstephend-sun commented on frontend/lib/src/features/admin_user_list/components/user_list_tile.dart
> +  @param users: contains user details.
```suggestion
  @param user: contains user details.
```

2023-07-04 02:51 UTC, jstephend-sun approved these changes
Approved 

review time: 10mins
comments: 3
iteration: 1st review

2023-07-04 03:10 UTC, Dbulawan13 approved these changes
Approve PR #42 

Working:
- Able to delete user
- Clicking (X) or No button will close the modal
- Unable to delete admin accounts
- Toast message will appear after deleting a user account

https://github.com/framgia/sph-flutter/assets/86758474/a244120a-9373-4eb4-94b2-5a0ac0e33fd3

Testing Hours: 0.16
Comment: 0
Iteration: 0

2023-07-04 03:20 UTC, merged