[SIM_FLUTTER-82] [BE] Apply linters to the repository
framgia/sph-flutter pull request #5
Opened 2023-06-09 07:25 UTC by jescabillas

**Issue Link**
- [BackLog](https://framgiaph.backlog.com/view/SIM_FLUTTER-82)

**Definition of done**
- [x] [BE] Apply linters to the repository

**Note**

To run the linters in laravel
- Make sure you're in the backend directory then run `./vendor/bin/pint` in the terminal

Or
1. Add keyboard shortcut in your vscode `file -> preferences -> keyboard Shortcuts`
2. Click on the file icon to open the json file of the keyboard shortcuts
3. Once open, add the following code to the file
````
[
  {
    "key": "ctrl+shift+l",
    "command": "workbench.action.tasks.runTask",
    "args": "Pint Formatter"
  }
]
````
4. Now all you have to do is hit `Ctrl + Shift + l` every time you want to run the linter

**Attachment**
![image](https://github.com/framgia/sph-flutter/assets/114911074/9d41b692-48b5-4480-908e-c460bfe71d65)

2023-06-09 09:30 UTC, karlolee50 requested changes

2023-06-09 09:30 UTC, karlolee50 commented on .vscode/tasks.json
> +}
add extra line here

2023-06-09 09:30 UTC, karlolee50 commented on backend/composer.lock
> +    "content-hash": "82d11cab70c32144370c683cf476478e",
do we need to push composer.lock? if not needed, can you update the .gitignore file?

2023-06-09 10:05 UTC, jescabillas commented on .vscode/tasks.json
> +}
Added extra line

2023-06-09 10:06 UTC, jescabillas commented on backend/composer.lock
> +    "content-hash": "82d11cab70c32144370c683cf476478e",
Added the composer.lock in .gitignore and reset the commits to exclude the changes in composer.lock

2023-06-09 10:13 UTC, karlolee50 submitted a review, later dismissed

2023-06-15 09:49 UTC, Dbulawan13 approved these changes
Approve PR #5 

Working:
- Linters is working properly
- Able to check if codes are pass or fail

![2023-06-15_17-29](https://github.com/framgia/sph-flutter/assets/86758474/22afdc3f-f014-4d4d-8a83-4ee77ba7983f)
![2023-06-15_17-26](https://github.com/framgia/sph-flutter/assets/86758474/02182cb4-bc89-4393-aadb-d29c99169736)

Testing Hours: 3
Comment: 0
Iteration: 0

2023-06-15 10:17 UTC, merged