Roberto/sim flutter 111
framgia/sph-flutter pull request #54
Opened 2023-07-07 03:25 UTC by rdelrosariojr

### Issue Links
- [backlog](https://framgiaph.backlog.com/view/SIM_FLUTTER-111)

### Definition of done
- [x] add account number in account table

### Notes
run `php artisan migrate`

### Recording
![image](https://github.com/framgia/sph-flutter/assets/97145763/eb8c03a9-3899-4b07-8763-8aeb477154e3)

2023-07-07 04:06 UTC, Dbulawan13 commented
Comment:

- [ ] Can you please create a seeder command that will populate the existing accounts with unique account number.
![2023-07-07_12-05](https://github.com/framgia/sph-flutter/assets/86758474/c8e98155-1c89-46b4-9e62-c852b449b173)

Comment: 1

2023-07-07 05:12 UTC, Dbulawan13 commented
Comment:

- [ ]  Is it possible for the seeder command to only update the account_number column? Currently, it creates another set of accounts, and the existing accounts still have 00000000000"as their account number.
![image](https://github.com/framgia/sph-flutter/assets/86758474/99363704-8e48-4f24-a256-5c46e8a73b88)

Comment: 1

2023-07-07 05:15 UTC, jstephend-sun requested changes
Requested Changes #54

review time: 5mins
comments: 2

2023-07-07 05:15 UTC, jstephend-sun commented on backend/database/migrations/2023_07_07_023101_add_account_number_to_accounts_table.php
> +            $table->string('account_number')->default('00000000000');
make this nullable and unique, dont put default so that we can have unique constraint

2023-07-07 05:15 UTC, jstephend-sun commented on backend/app/Http/Controllers/AccountController.php
> +            'account_number' => GenerateCode::generate(),
implement using trait instead

2023-07-07 07:09 UTC, Dbulawan13 approved these changes, later dismissed
Approve PR #54 

Working:
- Able to add new account_number column in account table
- Migration works properly
- Able to seed new and unique account_numbers in all existing accounts
- When user create new account, unique account_number will now be included

![2023-07-07_15-04](https://github.com/framgia/sph-flutter/assets/86758474/3949f8a6-01aa-4edd-8161-3c3ebb66a930)
![2023-07-07_15-03](https://github.com/framgia/sph-flutter/assets/86758474/dc4928dd-3491-486a-a24f-2f942f3992fc)
![2023-07-07_15-02](https://github.com/framgia/sph-flutter/assets/86758474/b119328a-dd25-4df0-85d2-cf27ab033149)
![2023-07-07_13-03](https://github.com/framgia/sph-flutter/assets/86758474/2d54f972-609f-45b3-8f57-b31ffd8a3f2d)

Testing Hours: 2
Comments: 3
Iterations: 3

2023-07-07 07:25 UTC, jstephend-sun requested changes
Requested Changes #54

total review time 8mins
total comments: 6
iteration: 2nd review

2023-07-07 07:25 UTC, jstephend-sun commented on backend/app/Traits/GenerateUniqueCode.php
> +class GenerateUniqueCode {
change to trait-like word/phrase
Generate is an action word

2023-07-07 07:25 UTC, jstephend-sun commented on backend/app/Http/Controllers/AccountController.php
> +            'account_number' => GenerateUniqueCode::generate(),
use as a trait

2023-07-07 07:25 UTC, jstephend-sun commented on backend/app/Models/Account.php
> +        'account_number'
trait not included in the model

2023-07-07 10:20 UTC, jstephend-sun requested changes
on `backend\app\Traits\Uuid.php`

change fn name to ` protected static function bootUuid()`
and remove `parent::boot();`, same with `bootUniqueCodeTrait`, dont include parent::boot

pls include this on the trait boot function 
for reference 
 `https://orkhan.dev/2020/08/17/using-traits-to-boot-and-initialize-eloquent-models/`

2023-07-07 10:20 UTC, jstephend-sun commented on backend/app/Http/Controllers/AccountController.php
> +            'account_number' => UniqueCodeTrait::generate(),
remove, account number should be automatically generated

2023-07-07 10:20 UTC, jstephend-sun commented on backend/app/Models/Account.php
> +        'account_number'
my code changes for this file

- adding the trait to the model
`use Uuid, UniqueCodeTrait;`

fn getUniqueCodeKeyName to specify to the trait which key to use
```
    /**
     * Indicates if the model's ID is auto-incrementing.
     *
     * @var bool
     */
    public $incrementing = false;

    /**
     * function for UniqueCodeTrait to retrieve the column 
     * name for to generate the unique code for
     */
    public function getUniqueCodeKeyName()
    {
        return "account_number";
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
```

2023-07-07 10:20 UTC, jstephend-sun commented on backend/app/Traits/UniqueCodeTrait.php
> + trait UniqueCodeTrait {
my changes for this file

highlighting `bootUniqueCodeTrait`, "bootTraitName" to be not in conflict with other traits
```
trait UniqueCodeTrait
{
    private static function _generateUniqueCode()
    {
        do {
            $code = (string)random_int(10000000000, 99999999999);
        } while (Account::where("account_number", $code)->exists());

        return $code;
    }

    /**
     * Boot function from Laravel.
     */
    protected static function bootUniqueCodeTrait()
    {
        // parent::boot();
        static::creating(function ($model) {
            if (empty($model->{$model->getUniqueCodeKeyName()})) {
                $code = static::_generateUniqueCode();

                $model->{$model->getUniqueCodeKeyName()} = $code;
            }
        });
    }

    /**
     * trait function for generating unique code
     * use case: seeder
     */
    public function generateUniqueCode()
    {
        return static::_generateUniqueCode();
    }
}
```

2023-07-07 10:20 UTC, jstephend-sun commented on backend/database/factories/AccountFactory.php
> +            'account_number' => GenerateUniqueCode::generate(),
remove, account number should be automatically generated

2023-07-07 10:20 UTC, jstephend-sun commented on backend/database/seeders/AccountSeeder.php
> +use App\Traits\GenerateUniqueCode;
remove, not used

2023-07-07 10:20 UTC, jstephend-sun commented on backend/database/seeders/AccountSeeder.php
> +use Illuminate\Database\Seeder;
remove, not used

2023-07-07 10:20 UTC, jstephend-sun commented on backend/database/seeders/fixes/AccountFixSeeder.php
> +            $account->account_number = GenerateUniqueCode::generate();
my code changes for this file

`$account->account_number = $account->generateUniqueCode();`

2023-07-10 03:33 UTC, jstephend-sun approved these changes
Approved #54

total review time 8mins
total comments: 6
iteration: 2nd review

2023-07-10 03:36 UTC, merged