[SIM_FLUTTER-105] [BE] Add Category in Withdrawal
framgia/sph-flutter pull request #59
Opened 2023-07-11 07:55 UTC by IanUrriza10

### Issue Links
- [backlog](https://framgiaph.backlog.com/view/SIM_FLUTTER-105)
- [slack]()

###  Notes

### Definition of done
- [x] Make transaction['category'] be able to handle 'FOOD', 'TRANSPORTATION', 'BILLS', 'SAVINGS', 'MISC'
- [x] Return error if there's a mismatch for type and category i.e. DEPT-TRANSPORTATION
- [x] Make a seeder fix class for the changes
- [x] Make a working migration file w/ rollback   

### Screenshots
![image](https://github.com/framgia/sph-flutter/assets/114897466/70854e05-d7a8-4921-a4dd-4a44c58f3461)
![image](https://github.com/framgia/sph-flutter/assets/114897466/9296726d-33cf-4980-8d2d-689830bfe2ad)
![image](https://github.com/framgia/sph-flutter/assets/114897466/3449ff87-65bf-44a0-932a-d9876f0d51d6)
![image](https://github.com/framgia/sph-flutter/assets/114897466/1e718080-e01e-49b7-a932-bdd4a0e37393)

2023-07-11 08:41 UTC, Dbulawan13 submitted a review, later dismissed
Approve PR #59 

Working:
- Migration is ok
- Able to update category and add new category options
  -  'FOOD', 'TRANSPORTATION', 'BILLS', 'SAVINGS', 'MISC' 
- Able to withdraw correct amount
- New category options are reflected in the database
- Able to minus current balance
- Unable to withdraw if user input non existing category
- Unable to withdraw if user input insufficient or 0 amount

![2023-07-11_16-37_1](https://github.com/framgia/sph-flutter/assets/86758474/9d365da3-b2fd-4634-b458-eff79a0a71dc)
![2023-07-11_16-37](https://github.com/framgia/sph-flutter/assets/86758474/270916ad-6c91-4755-a991-03f3f20fe579)
![2023-07-11_16-36_2](https://github.com/framgia/sph-flutter/assets/86758474/0c3442ca-e7a0-4443-83ea-0072631f1eb0)
![2023-07-11_16-36_1](https://github.com/framgia/sph-flutter/assets/86758474/8fe44e90-0369-495d-81ce-dd34cba41d3c)
![2023-07-11_16-36](https://github.com/framgia/sph-flutter/assets/86758474/8f01fd16-8dad-4f4e-86b4-8aeb97336b74)
![2023-07-11_16-35_1](https://github.com/framgia/sph-flutter/assets/86758474/3d604d58-f32d-450f-8f66-b82a1e682fc4)
![2023-07-11_16-35](https://github.com/framgia/sph-flutter/assets/86758474/0c2c7ae4-aca7-461e-bde3-31d594240ed6)
![2023-07-11_16-34](https://github.com/framgia/sph-flutter/assets/86758474/4ecebe7e-6239-4f00-8efa-f8c16d71cb58)
![2023-07-11_16-30](https://github.com/framgia/sph-flutter/assets/86758474/afcf7771-2e8b-42ca-b0a0-aeb97130c27c)

Testing Hours: 0.58
Comment: 0
Iteration: 0

2023-07-12 05:16 UTC, jstephend-sun requested changes
Requested Changes #59

review time: 15mins
comments: 2
iteration: 1st review

2023-07-12 05:16 UTC, jstephend-sun commented on backend/app/Http/Requests/TransactionPostRequest.php
> +            }],
refactor, separate this function

2023-07-12 05:16 UTC, jstephend-sun commented on backend/database/migrations/2023_07_11_035059_update_transaction_category.php
> +            }
seems inefficient, use SQL update here, rawsql if necessary, check eloquent first

2023-07-12 07:51 UTC, jstephend-sun reviewed
request

2023-07-12 07:51 UTC, jstephend-sun commented on backend/database/seeders/TransactionSeeder.php
> +            $category = $category_enums[rand(3, 7)];
add TODO: improve logic, use subcategories of enum

2023-07-12 07:58 UTC, jstephend-sun approved these changes
Approved #59

review time: 15mins
comments: 2
iteration: 1st review

2023-07-12 08:00 UTC, merged