[SIM_FLUTTER-102] [INTEGRATE] User can add new account type
framgia/sph-flutter pull request #62
Opened 2023-07-12 08:35 UTC by egiegarciano14

#### LINKS
- [backlog](https://framgiaph.backlog.com/view/SIM_FLUTTER-102)
- [slack](https://sun-philippine.slack.com/archives/C059L7XAXFB/p1689151037106919)

#### DOD
- User can create account

#### Note
- none

#### Screenshots 
![image](https://github.com/framgia/sph-flutter/assets/79126024/17b67196-2249-4bd9-a8f5-feb12a62cfb9)
![image](https://github.com/framgia/sph-flutter/assets/79126024/b216bf0e-bad2-479f-98fb-9ad279f28327)

2023-07-12 09:01 UTC, jstephend-sun requested changes
Requested Changes #62

review time: 15mins:
comments: 8
iteration: 1st review

2023-07-12 09:01 UTC, jstephend-sun commented on backend/config/enums.php
> +        'RECIPIENT' => 'Recipient',
remove, bills is not an account type, sender is not an account type, recipient is not an account type

2023-07-12 09:01 UTC, jstephend-sun commented on frontend/lib/src/controllers/add_account_controller.dart
> +List<String> accountTypes = ['Savings', 'Salary'];
transfer to the enum file, create function/variable to get the account type enum as List\<string>

2023-07-12 09:01 UTC, jstephend-sun commented on frontend/lib/src/features/dashboard/components/add_account_dialog.dart
> +    final dashboardController = Get.put(DashboardController());
add type on left hand

2023-07-12 09:01 UTC, jstephend-sun commented on frontend/lib/src/features/dashboard/components/add_account_dialog.dart
> +    final accountController = Get.put(AddAccountController());
use controller for accountController since this widget is mainly for the addaccount

2023-07-12 09:01 UTC, jstephend-sun commented on frontend/lib/src/services/account_service.dart
> +    return res.statusCode == HttpStatus.created;
return the whole response

2023-07-12 09:01 UTC, jstephend-sun commented on frontend/lib/src/models/account.dart
> +        "account_type": accountType.jsonValue,
i think no need for this, can just use `.name`

2023-07-12 09:01 UTC, jstephend-sun commented on backend/config/enums.php
> +        'SALARY' => 'Salary',
use full caps value

2023-07-12 09:01 UTC, jstephend-sun commented on frontend/lib/src/enums/account_enum.dart
> +}
just use SAVINGS, SALARY ...
i think no need for other parts

2023-07-12 09:11 UTC, Dbulawan13 approved these changes, later dismissed
Approve PR #62 

Working:
- Able to add savings and salary account
- Unable to create account if account name is empty
- Created account will automatically display in the lists of accounts

![2023-07-12_17-10](https://github.com/framgia/sph-flutter/assets/86758474/d5896c4a-59d5-4c3f-bd6b-e86134401a0c)

https://github.com/framgia/sph-flutter/assets/86758474/7ae4a577-0944-4934-8950-4892d1ba4cea

Testing Hours: 0.16
Comment: 0
Iteration: 0

2023-07-13 07:06 UTC, jstephend-sun requested changes
Requested Changes #62

total review time: 20mins:
comments: 8 +3
iteration: 2nd review

2023-07-13 07:06 UTC, jstephend-sun commented on frontend/lib/src/enums/account_enum.dart
> +}
put enum on top since the file is for enums mainly

2023-07-13 07:06 UTC, jstephend-sun commented on frontend/lib/src/enums/account_enum.dart
> +}
use extension instead

![image](https://github.com/framgia/sph-flutter/assets/95029803/40c57894-8cf5-49e9-a0a4-d6d155880c0c)

2023-07-13 07:06 UTC, jstephend-sun commented on frontend/lib/src/controllers/add_account_controller.dart
> +  Future<Account?> addUserAccount(Account account) async {
return whole response, FE can use the error response from BE if any field validation fails

2023-07-13 08:48 UTC, jstephend-sun approved these changes
Approved #62

total review time: 20mins:
comments: 10 (8 + 2)
iteration: 2nd review

2023-07-13 08:50 UTC, merged