[SIM_FLUTTER-56] [Integrate] Implement user filter by category/type of transaction
framgia/sph-flutter pull request #66
Opened 2023-07-13 09:54 UTC by jescabillas

### Links
[Backlog](https://framgiaph.backlog.com/view/SIM_FLUTTER-56)

### Definition of done
- [x] User will be able to filter the transaction history by type
- [x] Transaction history list will update accordingly based from transaction type

### Notes
None

### Recordings

https://github.com/framgia/sph-flutter/assets/114911074/006a6080-7c0a-48ae-8a23-1f27163d3100

2023-07-13 10:08 UTC, Dbulawan13 commented
Comment:

- [ ] Unable to run the application. An error will occur

![image](https://github.com/framgia/sph-flutter/assets/86758474/56935dc7-f9d4-4a75-9fc3-da7ac48c7e46)
![2023-07-13_18-07](https://github.com/framgia/sph-flutter/assets/86758474/b4d3352f-15f4-4cbb-a3a6-3c43d3945827)

Comment: 1

2023-07-14 02:56 UTC, Dbulawan13 commented
Comment:

- [ ] By default, it should display all the transaction history. 
![2023-07-14_10-29](https://github.com/framgia/sph-flutter/assets/86758474/aa3e97e3-0af4-43e0-a9cc-38c3b13a1ef5)

- [ ] By default, filter by category should be blank first
![2023-07-14_10-27_1](https://github.com/framgia/sph-flutter/assets/86758474/d3a68fea-c310-4327-8ded-dd4bccb5134c)

- [ ] Only able to display maximum of 10 transactions maybe with this reason it received transaction was not displayed
![image](https://github.com/framgia/sph-flutter/assets/86758474/47148e27-1d1a-4b16-b86d-9648f990e56f)

- [ ] It display duplicate transactions
![2023-07-14_10-27](https://github.com/framgia/sph-flutter/assets/86758474/d2b9717b-c407-4533-8f9a-56f37d30a2df)

- [ ] Filter transaction should reset when user visit another account. Or by default it should display first all transactions and filter field should be blank

https://github.com/framgia/sph-flutter/assets/86758474/11d3ffb6-a391-4b76-8b04-5849c6a1e9ad

Comment: 5

2023-07-14 09:52 UTC, Dbulawan13 commented
Comment:

- [ ] Instead of displaying the text 'All Transactions,' please display it as blank. This will align with the default blank display of the filter by date.
![2023-07-14_17-41](https://github.com/framgia/sph-flutter/assets/86758474/a946fe50-2959-440c-93e7-d24ad087a3f6)

Comment: 1

2023-07-17 06:09 UTC, Dbulawan13 approved these changes, later dismissed
Approve PR #66 

Working:
- Able to filter category 
   - by All Transaction
   - Credit
   - Dept
   - Transfer 
- All transaction will be selected by default
- All transaction history will be displayed by default
- Once user redirect to another accounts transaction. Filtered category will reset

https://github.com/framgia/sph-flutter/assets/86758474/6a3a9bdf-9970-41c1-a517-981d109405f5

Testing Hours: 2
Comments: 7
Iterations: 3

2023-07-18 09:34 UTC, Dbulawan13 approved these changes, later dismissed

2023-07-18 10:00 UTC, jstephend-sun requested changes
Requested Changes #66

review time: 15mins
comments: 5
iteration: 1st review

2023-07-18 10:00 UTC, jstephend-sun commented on frontend/lib/src/features/transaction_history/transaction_history.dart
> +    return Obx(
do not wrap FutureBuilder here with Obx

Obx doesnt have an observable child close to it

this was not rebased properly

2023-07-18 10:00 UTC, jstephend-sun commented on frontend/lib/src/features/transaction_history/transaction_history.dart
> +                            ),
refactor enum `TransactionTypes`
to be similar implementation with `AccountType` enum which is using enhanced enum implementation

use `fromJson` to signify that the static constructor is for the BE data.

2023-07-18 10:00 UTC, jstephend-sun commented on frontend/lib/src/features/account_details/account_details_page.dart
> +                            transactionController
this causes unnecessary double request on the transactions api endpoint

[screen-capture.webm](https://github.com/framgia/sph-flutter/assets/95029803/795502bc-c3dd-467f-aa9d-f8f708a312ad)

2023-07-18 10:00 UTC, jstephend-sun commented on frontend/lib/src/features/transaction_history/transaction_history.dart
> +                          .toList(),
refactor into a function in the enum file, to get the values of the enum as list of string

2023-07-18 10:00 UTC, jstephend-sun commented on frontend/lib/src/features/transaction_history/transaction_history.dart
> +                              capitalizeFirstLetter(type.name) == convertValue,
refactor as static enum constructor

use `fromValue`
contrary from `fromJson`
fromValue signifies that this is from the converted String of the enum

ex.
json = DEPT (which is equal to enum.name)
value = Debit

fromJson("DEPT") returns TransactionType.DEPT
fromValue("Debit") returns TransactionType.DEPT

2023-07-19 03:59 UTC, jescabillas commented on frontend/lib/src/features/transaction_history/transaction_history.dart
> +                              capitalizeFirstLetter(type.name) == convertValue,
adjusted

2023-07-19 03:59 UTC, jescabillas commented on frontend/lib/src/features/transaction_history/transaction_history.dart
> +                          .toList(),
adjusted

2023-07-19 04:00 UTC, jescabillas commented on frontend/lib/src/features/transaction_history/transaction_history.dart
> +                            ),
adjusted

2023-07-19 04:07 UTC, jescabillas commented on frontend/lib/src/features/transaction_history/transaction_history.dart
> +    return Obx(
adjusted

2023-07-19 04:07 UTC, jescabillas commented on frontend/lib/src/features/account_details/account_details_page.dart
> +                            transactionController
adjusted

2023-07-19 04:42 UTC, jstephend-sun approved these changes
Approved #66

review time: 15mins
comments: 5
iteration: 1st review

2023-07-19 04:53 UTC, merged