[SIM_FLUTTER-15] [FE] Create Admin User List Page
framgia/sph-flutter pull request #8
Opened 2023-06-13 09:17 UTC by IanUrriza10

**Issue Link**
- [BackLog](https://framgiaph.backlog.com/view/SIM_FLUTTER-15)

**Definition of Done**
- [x] [FE] Create Admin User List Page
- [x] [FE] Create Delete User Dialog 
 
**Note**
 - Image is temporary as i could not find the actual logo file

**Attachment**
![image](https://github.com/framgia/sph-flutter/assets/114897466/09a11635-2a46-4568-9a42-1bbfe6238e83)
![image](https://github.com/framgia/sph-flutter/assets/114897466/c4a4d9a0-9919-4bce-8be0-bcb1719eb985)
![image](https://github.com/framgia/sph-flutter/assets/114897466/c4a0eba2-60cb-44a7-9a08-5195e9f0ae78)

2023-06-13 09:46 UTC, Dbulawan13 commented
Comment:
- [ ] Please apply the correct logo design and remove the white background color.

![2023-06-13_17-42](https://github.com/framgia/sph-flutter/assets/86758474/ca71c952-3b51-42eb-af4f-12d540337d32)

- [ ] Please apply the footer design to match the design in Figma.

![2023-06-13_17-42_1](https://github.com/framgia/sph-flutter/assets/86758474/085ef0f1-6a7d-4c28-bf9f-ce2f8ec7085b)

- [ ] Please apply the correct alignment for the modal buttons.

![image](https://github.com/framgia/sph-flutter/assets/86758474/1bababfa-409e-436c-bf75-af232447f845)

- [ ] When scrolling up and down, the list part should not overlap/clash with the search field.

https://github.com/framgia/sph-flutter/assets/86758474/74782070-cbb6-4eec-b48e-4f34a397076e

Testing Hours: 0.23
Comments: 4

2023-06-15 02:50 UTC, Dbulawan13 commented
Comment:

- [ ] Please apply the correct delete/trashcan icon based on the figma
![image](https://github.com/framgia/sph-flutter/assets/86758474/278c378a-79a0-4e2c-aa81-9940de387b3a)

Figma:
https://www.figma.com/file/uzAwGmOCLvGbReXshnT3UN/SAVINGS-APP?type=design&node-id=489-362&t=tfLDGtzmPMTOm1OI-0
![image](https://github.com/framgia/sph-flutter/assets/86758474/3ab87de3-c135-4b99-8af4-d39f34db698c)

- [ ] Please apply the correct background color which is `white` or #FFFFFF of the modal.
![image](https://github.com/framgia/sph-flutter/assets/86758474/13e4706d-a09f-47d2-b02e-37fb91fedcd5)

Comments: 2

2023-06-15 06:35 UTC, Dbulawan13 commented
Initial Approved PR #8 

Working:
- Able to create admin user list page
- Able to scroll up and down
- Delete icon is clickable
- Able to open modal once delete button is clicked

https://github.com/framgia/sph-flutter/assets/86758474/ecde0d8a-468a-435c-ba9e-087bfd35c74e

Testing hours: 2
Comments: 5
Iterations: 2

2023-06-16 05:46 UTC, Dbulawan13 submitted a review, later dismissed
Initial Approved PR https://github.com/framgia/sph-flutter/pull/8

Working:
- Able to create admin user list page
- Able to scroll up and down
- Delete icon is clickable
- Able to open modal once delete button is clicked
- The search bar now matches the design in Figma.

![image](https://github.com/framgia/sph-flutter/assets/86758474/19d06f7c-3f1d-431b-9367-604fae37de71)

Testing Hours: 2.1
Comments: 5
Iterations: 2

2023-06-19 02:59 UTC, jstephend-sun requested changes
Requested Changes #8

review time: 30mins
comments: 8
iteration: 1st comment

2023-06-19 02:59 UTC, jstephend-sun commented on frontend/lib/src/components/input/search_field.dart
>    final String name;
```suggestion
  });
  
  final String name;
```
space

2023-06-19 02:59 UTC, jstephend-sun commented on frontend/lib/src/components/input/search_field.dart
> +    this.validator,
add @param descriptions i above comments for
validator (if InputField doesnt have it yet)
and yPaddings

2023-06-19 02:59 UTC, jstephend-sun commented on frontend/lib/main.dart
> +          ElevatedButton(
based on figma design, there is a navbar tab for the admin user list, it can already be separated from this temporary setup

2023-06-19 02:59 UTC, jstephend-sun commented on frontend/lib/src/features/admin_user_list/admin_user_list_page.dart
> +  final List<String> userList = [
add TODO comment fopr the user list variable

2023-06-19 02:59 UTC, jstephend-sun commented on frontend/lib/src/features/admin_user_list/admin_user_list_page.dart
> +  AdminUserListPage({super.key});
put constructor on first line for consistency with other pages

2023-06-19 02:59 UTC, jstephend-sun commented on frontend/lib/src/features/admin_user_list/admin_user_list_page.dart
> +      bottomNavigationBar: CurvedNavigationBar(
you produced 2 navbars in the app, remove

2023-06-19 02:59 UTC, jstephend-sun commented on frontend/lib/src/features/admin_user_list/components/user_delete_dialog.dart
> +  @override
```suggestion
  const UserDeleteDialog({super.key});
  
  @override
```
space

2023-06-19 02:59 UTC, jstephend-sun commented on frontend/lib/src/features/admin_user_list/components/user_delete_dialog.dart
> +                    Navigator.of(context).pop();
use Getx function here, i think Get.pop or something

2023-06-19 02:59 UTC, jstephend-sun commented on frontend/lib/src/features/admin_user_list/components/user_delete_dialog.dart
> +                      fontFamily: 'Nunito',
fontfamily is already default nunito

2023-06-19 02:59 UTC, jstephend-sun commented on frontend/lib/src/features/admin_user_list/components/user_delete_dialog.dart
> +                    Navigator.of(context).pop();
same here with Getx method

2023-06-19 02:59 UTC, jstephend-sun commented on frontend/lib/src/features/admin_user_list/components/user_delete_dialog.dart
> +                    Navigator.of(context).pop();
same here with Getx method

2023-06-19 02:59 UTC, jstephend-sun commented on frontend/lib/src/features/admin_user_list/components/user_list_card.dart
> +  const UserListCard({super.key, required this.name});
same here, constructor first on first line

2023-06-19 02:59 UTC, jstephend-sun commented on frontend/lib/src/features/admin_user_list/components/user_list_card.dart
> +        icon: Image.asset('assets/images/trash-icon.png'),
use svg instead, the icon is pixelated

2023-06-19 05:58 UTC, Dbulawan13 submitted a review, later dismissed
Approve PR #8 

Working:
- Able to create admin user list page
- Comments have been fixed

Note: Will recheck in master branch about the "+" button once merge

![2023-06-19_13-48_1](https://github.com/framgia/sph-flutter/assets/86758474/f65cd60d-265b-493a-b422-e27b77823f37)
![2023-06-19_13-48](https://github.com/framgia/sph-flutter/assets/86758474/28b82ddd-81e9-47ab-bfcb-88e922485362)

Testing Hours: 2
Comments: 8
Iterations: 4

2023-06-19 08:27 UTC, jstephend-sun requested changes
Requested Changes #8

review time: 5mins
comments: 6
iteration: 2nd comment

2023-06-19 08:27 UTC, jstephend-sun commented on frontend/lib/main.dart
> +import 'package:frontend/src/navigators/profile_screen_navigator.dart';
unused import

2023-06-19 08:27 UTC, jstephend-sun commented on frontend/lib/main.dart
>                settingsAppNav.currentState?.pushNamed('/searchfieldpage');
TODO comment got removed

2023-06-19 08:27 UTC, jstephend-sun commented on frontend/lib/src/components/input/search_field.dart
> +  PARAMETER name: similar to html name attribute, provides the form widget the key to assign its value
lets use @param for consistency

2023-06-19 08:27 UTC, jstephend-sun commented on frontend/lib/src/components/input/search_field.dart
> +  final double yPadding;
reorder following the constructor order

2023-06-19 08:27 UTC, jstephend-sun commented on frontend/lib/src/features/admin_user_list/admin_user_list_page.dart
> +                ),
use SizedBox here since it only has height

2023-06-19 08:27 UTC, jstephend-sun commented on frontend/lib/src/features/admin_user_list/admin_user_list_page.dart
> +class AdminUserListPage extends StatelessWidget {
provide some descriptions on the widgets on this pr

2023-06-19 10:23 UTC, jstephend-sun approved these changes
Approved #8

review time: 5mins
comments: 6
iteration: 2nd comment

2023-06-19 10:25 UTC, merged